blank_issues_enabled: false
contact_links:
  - name: xDrip Discussions
    url: https://github.com/NightscoutFoundation/xDrip/discussions
    about: If you need xDrip support (bug report, feature request, or questions), please post here.   
